//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHW_PLANTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int DeliveryId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int DeliveryMail { get; set; }
        public int DeliveryRead { get; set; }
        public int DeliveryCompleted { get; set; }
        public Nullable<System.DateTime> DeliveryCompletedDate { get; set; }
        public int DeliveryUserId { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
