//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHW_PLANTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationDetail
    {
        public int InstallationId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public int InstallationMail { get; set; }
        public int InstalllationRead { get; set; }
        public Nullable<System.DateTime> InstallationCompletedDate { get; set; }
        public int InstallationUserId { get; set; }
        public int InstallationCompleted { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
