//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHW_PLANTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDDdetail
    {
        public int LDId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime LDDueDate { get; set; }
        public int LDMail { get; set; }
        public int LDRead { get; set; }
        public Nullable<System.DateTime> LDCompletedDate { get; set; }
        public int LDUserId { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
