//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHW_PLANTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentMail { get; set; }
        public int PaymentRead { get; set; }
        public int PaymentCompleted { get; set; }
        public Nullable<System.DateTime> PaymentCompletedDate { get; set; }
        public int PaymentUserId { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
